## 1. Understand the dataset

In [6]:
import pandas as pd

DATA_DIR = "data/fitzpatrick17k.csv"
# Load data
df = pd.read_csv(DATA_DIR)

In [3]:
df.shape # (16577 rows, 9 columns)

(16577, 9)

In [5]:
df.head()

,md5hash,fitzpatrick_scale,fitzpatrick_centaur,label,nine_partition_label,three_partition_label,qc,url,url_alphanum
0,5e82a45bc5d78bd24ae9202d194423f8,3,3,drug induced pigmentary changes,inflammatory,non-neoplastic,NaN,https://www.dermaamin.com/site/images/clinical...,httpwwwdermaamincomsiteimagesclinicalpicmminoc...
1,fa2911a9b13b6f8af79cb700937cc14f,1,1,photodermatoses,inflammatory,non-neoplastic,NaN,https://www.dermaamin.com/site/images/clinical...,httpwwwdermaamincomsiteimagesclinicalpicpphoto...
2,d2bac3c9e4499032ca8e9b07c7d3bc40,2,3,dermatofibroma,benign dermal,benign,NaN,https://www.dermaamin.com/site/images/clinical...,httpwwwdermaamincomsiteimagesclinicalpicdderma...
3,0a94359e7eaacd7178e06b2823777789,1,1,psoriasis,inflammatory,non-neoplastic,NaN,https://www.dermaamin.com/site/images/clinical...,httpwwwdermaamincomsiteimagesclinicalpicppsori...
4,a39ec3b1f22c08a421fa20535e037bba,1,1,psoriasis,inflammatory,non-neoplastic,NaN,https://www.dermaamin.com/site/images/clinical...,httpwwwdermaamincomsiteimagesclinicalpicppsori...

The Fitzpatrick scale served as the basis for skin color in emojis and, more recently, the Fitzpatrick scale has been used in computer vision applications to evaluate algorithmic fairness and model accuracy. The annotated images represent 114 skin conditions with at least 53 images and a maximum of 653 images per skin condition.

In [ ]:
pd.set_option('display.max_rows', 120) # to see all of the labels
df['label'].value_counts(ascending=True)

label
xanthomas                                                 53
pustular psoriasis                                        53
pilomatricoma                                             53
erythema elevatum diutinum                                55
paronychia                                                59
port wine stain                                           59
disseminated actinic porokeratosis                        60
livedo reticularis                                        60
langerhans cell histiocytosis                             60
perioral dermatitis                                       61
basal cell carcinoma morpheiform                          62
behcets disease                                           63
becker nevus                                              63
ichthyosis vulgaris                                       65
sun damaged skin                                          66
solid cystic basal cell carcinoma                         66
factitial dermatitis                                      66
striae                                                    67
acquired autoimmune bullous diseaseherpes gestationis     67
myiasis                                                   67
congenital nevus                                          68
neurodermatitis                                           69
stasis edema                                              69
seborrheic keratosis                                      69
epidermolysis bullosa                                     70
drug induced pigmentary changes                           71
aplasia cutis                                             72
naevus comedonicus                                        73
neurotic excoriations                                     73
pityriasis lichenoides chronica                           73
tick bite                                                 73
granuloma pyogenic                                        75
lichen amyloidosis                                        77
keratosis pilaris                                         78
porokeratosis of mibelli                                  78
dermatofibroma                                            79
mucous cyst                                               79
calcinosis cutis                                          80
erythema nodosum                                          81
xeroderma pigmentosum                                     81
halo nevus                                                82
lentigo maligna                                           83
dyshidrotic eczema                                        83
nevocytic nevus                                           86
erythema annulare centrifigum                             88
hidradenitis                                              90
epidermal nevus                                           91
rhinophyma                                                91
acrodermatitis enteropathica                              92
acanthosis nigricans                                      92
mucinosis                                                 92
pilar cyst                                                93
nevus sebaceous of jadassohn                              95
lichen simplex                                            97
lymphangioma                                             100
fordyce spots                                            100
rosacea                                                  102
incontinentia pigmenti                                   102
cheilitis                                                106
scleromyxedema                                           108
lupus subacute                                           111
malignant melanoma                                       111
urticaria pigmentosa                                     112
milia                                                    112
stevens johnson syndrome                                 113
pyogenic granuloma                                       113
superficial spreading melanoma ssm                       118
necrobiosis lipoidica                                    123
fixed eruptions                                          125
seborrheic dermatitis                                    126
telangiectases                                           126
ehlers danlos syndrome                                   127
syringoma                                                127
porphyria                                                127
lyme disease                                             129
tuberous sclerosis                                       141
juvenile xanthogranuloma                                 149
papilomatosis confluentes and reticulate                 150
urticaria                                                151
dermatomyositis                                          151
pediculosis lids                                         151
tungiasis                                                152
dariers disease                                          153
kaposi sarcoma                                           156
keloid                                                   156
vitiligo                                                 166
prurigo nodularis                                        170
hailey hailey disease                                    174
actinic keratosis                                        175
mycosis fungoides                                        182
porokeratosis actinic                                    183
acne                                                     183
neurofibromatosis                                        189
pityriasis rosea                                         193
drug eruption                                            200
eczema                                                   204
granuloma annulare                                       211
erythema multiforme                                      236
nematode infection                                       260
melanoma                                                 261
pityriasis rubra pilaris                                 278
scleroderma                                              309
acne vulgaris                                            335
scabies                                                  339
folliculitis                                             342
photodermatoses                                          348
sarcoidosis                                              349
neutrophilic dermatoses                                  361
lupus erythematosus                                      410
allergic contact dermatitis                              430
basal cell carcinoma                                     468
lichen planus                                            491
squamous cell carcinoma                                  581
psoriasis                                                653
Name: count, dtype: int64

In [18]:
df['nine_partition_label'].value_counts(ascending=True)

nine_partition_label
malignant dermal                  156
malignant cutaneous lymphoma      182
benign melanocyte                 236
malignant melanoma                573
benign epidermal                  931
benign dermal                    1067
genodermatoses                   1194
malignant epidermal              1352
inflammatory                    10886
Name: count, dtype: int64

- Non-Neoplastic : Not a tumor/new growth                   -> Normal
- Benign	     : Non-cancerous new growth (neoplasm) -> Neutral
- Malignant	     : Cancerous new growth (neoplasm).    -> Dangerous

In [ ]:
df['three_partition_label'].value_counts(ascending=True)

three_partition_label
benign             2234
malignant          2263
non-neoplastic    12080
Name: count, dtype: int64

- 1-2: Very light to light skin (Type I-II) - Burns easily, rarely tans
- 3-4: Medium skin (Type III-IV) - Tans gradually, sometimes burns
- 5-6: Dark to very dark skin (Type V-VI) - Tans easily, rarely burns
- -1: Unknown

In [16]:
df['fitzpatrick_scale'].value_counts(ascending=False)

fitzpatrick_scale
 2    4808
 3    3308
 1    2947
 4    2781
 5    1533
 6     635
-1     565
Name: count, dtype: int64

In [30]:
pd.crosstab(df['fitzpatrick_scale'], df['three_partition_label'], margins=True, margins_name='Total')

three_partition_label  benign  malignant  non-neoplastic  Total
fitzpatrick_scale
-1                         74        103             388    565
1                         444        453            2050   2947
2                         671        742            3395   4808
3                         475        456            2377   3308
4                         367        301            2113   2781
5                         159        147            1227   1533
6                          44         61             530    635
Total                    2234       2263           12080  16577